# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# compile C with /opt/microchip/xc32/v1.34/bin/xc32-gcc
C_FLAGS = -O2 -g -DNDEBUG   -Os -fdata-sections -ffunction-sections -mprocessor=32MX795F512L

C_DEFINES = -DENABLE_MOTE0_SUPPORT -D__32MX795F512L__ -D__PIC32MX__

C_INCLUDES = -I/home/juan/microchip/harmony/v1_06/framework -I/home/juan/git/rexlab-ecc-acelerated/lib-pic32-Rexlab -I/home/juan/git/rexlab-ecc-acelerated/lib-pic32-Rexlab/base -I/home/juan/git/rexlab-ecc-acelerated/lib-pic32-Rexlab/framework -I/home/juan/git/rexlab-ecc-acelerated/help 

